#!/usr/bin/env bash
# Install SocialBlocker: a `socialblocker` command that works from any working
# directory, plus (optionally) the enforcement daemon as a systemd service.
#
#   sudo ./install.sh           copy the code to /opt/socialblocker (default)
#   sudo ./install.sh --link    run *this* checkout in place, wherever it lives
set -euo pipefail

BIN=/usr/local/bin/socialblocker
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE=copy

usage() {
  sed -n '2,6p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --link) MODE=link ;;
    --copy) MODE=copy ;;
    -h|--help) usage 0 ;;
    *) echo "unknown option: $1" >&2; usage 2 ;;
  esac
  shift
done

# Where the installed command and the daemon will import the package from.
if [[ $MODE == link ]]; then PREFIX="$SRC_DIR"; else PREFIX=/opt/socialblocker; fi

if [[ $EUID -ne 0 ]]; then
  echo "Please run with sudo: sudo ./install.sh" >&2
  exit 1
fi

# PYTHONPATH is passed unquoted through `env` in both the launcher and the
# systemd unit, so a path with spaces would silently split into two arguments.
if [[ "$PREFIX" == *[[:space:]]* ]]; then
  echo "!! Path contains spaces: $PREFIX" >&2
  echo "   Move the project to a space-free path, or use the default copy install." >&2
  exit 1
fi

# --- Dependencies: Python 3 + Tkinter (for the GUI) ------------------------
ensure_deps() {
  if ! command -v python3 >/dev/null 2>&1; then
    echo "==> python3 not found — installing it too"
  fi
  if python3 -c "import tkinter" >/dev/null 2>&1; then
    echo "==> Tkinter already present — GUI ready"
    return
  fi

  echo "==> Tkinter missing — installing it via your package manager"
  if   command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq && apt-get install -y python3 python3-tk
  elif command -v dnf     >/dev/null 2>&1; then
    dnf install -y python3 python3-tkinter
  elif command -v yum     >/dev/null 2>&1; then
    yum install -y python3 python3-tkinter
  elif command -v pacman  >/dev/null 2>&1; then
    pacman -Sy --noconfirm python tk
  elif command -v zypper  >/dev/null 2>&1; then
    zypper install -y python3 python3-tk
  elif command -v apk     >/dev/null 2>&1; then
    apk add python3 python3-tkinter
  else
    echo "!! Could not detect a package manager. Install Tkinter manually:" >&2
    echo "     Debian/Ubuntu: python3-tk   Fedora: python3-tkinter   Arch: tk" >&2
  fi

  if python3 -c "import tkinter" >/dev/null 2>&1; then
    echo "==> Tkinter installed — GUI ready"
  else
    echo "!! Tkinter still not importable; the CLI works, GUI won't until fixed." >&2
  fi
}

echo "==> Checking dependencies"
ensure_deps

# The filesystem the code lives on. "/" means the root filesystem, which systemd
# can always count on at boot; anything else has to be waited for explicitly.
code_mount() { findmnt -no TARGET --target "$PREFIX" 2>/dev/null || echo /; }

# --- Place the code --------------------------------------------------------
if [[ $MODE == copy ]]; then
  echo "==> Installing to $PREFIX"
  mkdir -p "$PREFIX"
  cp -r "$SRC_DIR/socialblocker" "$SRC_DIR/data" "$PREFIX/"
else
  echo "==> Linking $PREFIX (runs in place — no copy, so edits are live)"
  owner="$(stat -c %U "$PREFIX")"
  if [[ "$owner" != root ]]; then
    echo "    warning: the root daemon will execute code owned by '$owner'."
    echo "             Anyone who can write there can run code as root. Prefer the"
    echo "             default copy install on a shared or untrusted machine."
  fi
  if [[ "$(code_mount)" != "/" ]]; then
    echo "    note: the code is on $(code_mount), not the root filesystem — the unit"
    echo "          gets RequiresMountsFor so the daemon waits for that disk instead"
    echo "          of crash-looping at boot. If the disk is absent, nothing blocks."
  fi
  if [[ -d /opt/socialblocker ]]; then
    echo "    note: the old copy in /opt/socialblocker is now unused."
    echo "          Remove it when you're happy: sudo rm -rf /opt/socialblocker"
  fi
fi

# --- The `socialblocker` command (this is what makes cwd irrelevant) -------
echo "==> Creating $BIN"
cat > "$BIN" <<EOF
#!/usr/bin/env bash
# Generated by install.sh — runs the code in $PREFIX from any directory.
exec env PYTHONPATH=$PREFIX /usr/bin/python3 -m socialblocker "\$@"
EOF
chmod +x "$BIN"

echo "==> Installing systemd service"
UNIT=/etc/systemd/system/socialblocker.service
sed "s#/opt/socialblocker#$PREFIX#g" "$SRC_DIR/systemd/socialblocker.service" > "$UNIT"
# ensure the daemon can import the package
sed -i "s#ExecStart=/usr/bin/python3#ExecStart=/usr/bin/env PYTHONPATH=$PREFIX /usr/bin/python3#" "$UNIT"
# A linked install may live on a second disk; without this the daemon starts
# before the mount exists and Restart=always turns that into a crash loop.
if [[ "$(code_mount)" != "/" ]]; then
  sed -i "/^After=/a RequiresMountsFor=$PREFIX" "$UNIT"
fi
systemctl daemon-reload

# An already-running daemon keeps executing the old code until it is restarted —
# the single most common "my change did nothing" surprise.
if systemctl is-active --quiet socialblocker; then
  echo "==> Restarting the running daemon so the new code takes effect"
  systemctl restart socialblocker
fi

echo
echo "Installed ($MODE mode, code in $PREFIX)."
echo "The 'socialblocker' command now works from any directory."
if [[ $MODE == copy ]]; then
  echo "Editing the checkout does nothing until you re-run install.sh."
  echo "For live edits instead:  sudo ./install.sh --link"
fi
echo
echo "Quick start:"
echo "  socialblocker status"
echo "  socialblocker mode blacklist          # block distractions all day"
echo "  socialblocker focus 90 --locked       # 90-min locked whitelist focus"
echo
echo "Enable the always-on daemon (needed for schedules + locked-mode repair):"
echo "  sudo systemctl enable --now socialblocker"
echo
echo "Start blocking automatically with the computer:"
echo "  sudo socialblocker autostart --session on --minutes 300 --blacklist"
echo "  sudo socialblocker autostart --service on   # daemon at boot"
echo "  socialblocker autostart --gui on            # open the app at login"
